services:
  db:
    image: mysql:8.0
    container_name: salessavvy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 8277006863
      MYSQL_DATABASE: Ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: salessavvy-backend
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 8277006863
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_ENABLED: false
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      JWT_SECRET: our-very-long-secure-secret-key-for-production-12345678901234567890
      JWT_EXPIRATION: 3600000
      RAZORPAY_KEY_ID: rzp_test_RIC94zkP6AVH6a
      RAZORPAY_KEY_SECRET: kHJMjcgpGpNxf44TH4Jbmx2k
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
    restart: unless-stopped

  frontend:
    build: ./Ecommerce
    container_name: salessavvy-frontend
    ports:
      - "5173:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  mysql_data:
